apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h2cg2mawl-go
  janus-idp.io/tekton: h2cg2mawl-go
  backstage.io/kubernetes-id: h2cg2mawl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h2cg2mawl-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
